# Generated by Django 3.1.4 on 2020-12-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.UpperCharField


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'Воздушное судно', 'verbose_name_plural': 'Воздушные суда'},
        ),
        migrations.AlterModelOptions(
            name='aircrafttype',
            options={'verbose_name': 'Тип воздушного судна', 'verbose_name_plural': 'Типы воздушных судов'},
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='aircrafttype',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircrafttype_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.CreateModel(
            name='FlightSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название лётного отряда')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flightsquad_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flightsquad_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Лётный отряд',
                'verbose_name_plural': 'Лётные отряды',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название аэропорта')),
                ('icao_code', lib.UpperCharField.UpperCharField(max_length=4, unique=True, verbose_name='ICAO код')),
                ('iata_code', lib.UpperCharField.UpperCharField(max_length=4, unique=True, verbose_name='IATA код')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airport_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
    ]
